version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10.0-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: setup yarn
          command: |
            sudo npm install -g yarn@1.6.0

      - run: yarn install --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn lint
      - run:
          name: Format
          command: |
            yarn format;
            git diff --exit-code --quiet;
            if [ $? = 1 ]; then
              echo 'Unformat file(s) found.';
              exit 1
            fi
      - run: yarn test:coverage
      - store_artifacts:
          path: ~/repo/coverage/lcov-report/

      - run:
          name: Add python3.7
          command: |
            curl -O https://www.python.org/ftp/python/3.7.1/Python-3.7.1.tgz
            tar xvfz Python-3.7.1.tgz
            cd Python-3.7.1/
            ./configure --prefix=/usr/local/python371 --with-ensurepip
            make
            sudo make install
            sudo ln -fs /usr/local/python371/bin/python3.7 /usr/bin/python

      - run:
          name: deploy
          command: |
            sudo apt-get -y -qq install awscli
            sudo npm install -g serverless
            ./deploy.sh
